version: "3.8"

services:
  # Node.js service
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    ports:
      - "3001:3001"
    network_mode: bridge
    volumes:
      - .:/app
